[theme]
primaryColor = "#556B2F"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#141414"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "error"

[server]
headless = true
port = 8501
enableXsrfProtection = true
enableCORS = false
