[theme]
primaryColor = "#3483fa"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "error"

[server]
headless = true
port = 8501
enableXsrfProtection = true
enableCORS = false
